import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ContactFormModal from '@/components/modals/contact-form'
import CreatePostModal from '@/components/modals/create-post-modal'
import { StoreProvider } from '@/stores/store-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Realm',
  description: 'Generated by us',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ContactFormModal />
          <CreatePostModal />
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
